---
server:
    install: '1'
    packages: [vim, git]
    timezone: Europe/Amsterdam
    locale: en_US.UTF-8
vagrant_local:
    install: '1'
    vm: { base_box: trusty64, hostname: sandbox.imanee.io, ip: 192.168.13.99, memory: '512', sharedfolder: ./, enableWindows: '1', useVagrantCloud: '1', syncType: nfs }
nginx:
    install: '1'
    docroot: /vagrant/demos/scripts
    servername: sandbox.imanee.io 192.168.13.99
php:
    install: '1'
    ppa: php5-5.6
    packages: [php5-cli, php5-gd, php5-imagick]

